a= str(input())
b=int(input())
c=float(input())
d=float(input())
e=int(input())
f=str(input())
g=int(input())
h=int(input())
li=[a,b,c,d,e,f,g,h]
print(['not eligible','eligible'][b>=18 and c>=7.0 and d>=75 and e==0 and g>=60 and h>=50])
